model_name_or_path: /mnt/nas-alinlp/ljy/models/Qwen2.5-Coder-7B-Instruct
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
dataset: motcode
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: /mnt/nas-alinlp/ljy/MoTCoder/output/Qwen2.5-Coder-7B-Instruct-sft-2e-06-mot
logging_steps: 1
save_strategy: steps
plot_loss: true
save_steps: 200
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-06
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
